version: "3.4"

services:
  back:
    # https://github.com/tairau/php-fpm-alpine PHP v8.0.8
    image: tairau/php-fpm-alpine:v2.2.3
    env_file: ./.env
    environment:
      OPCACHE_VALIDATE_TIMESTAMPS: "1"
    ports:
      - 80:8000
    # Первый можно использовать любой незанятый.
    command: php artisan serve --host 0.0.0.0
    volumes:
      - ./:/app:cached

  db:
    restart: "always"
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    # Если не нужны порты наружу и/или заняты, можно закомментировать.
